# Generated by Django 5.1 on 2024-08-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('performer', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('url', models.CharField(max_length=500)),
                ('embed_url', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/videos/')),
            ],
        ),
    ]
