# Generated by Django 5.1 on 2024-08-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activity_albums_article_experience_indexstory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
