# Generated by Django 5.1 on 2024-08-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_activity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/teachers/'),
        ),
    ]
