# Generated by Django 5.1 on 2024-08-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teacher_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='price',
            new_name='price_type',
        ),
    ]
