# Generated by Django 5.1 on 2024-08-17 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_price_activity_price_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
    ]
