# Generated by Django 5.1 on 2024-08-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_album_description_album_tag_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.JSONField(default='default'),
            preserve_default=False,
        ),
    ]
