# Generated by Django 5.1 on 2024-08-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_album_tag_album_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.CharField(max_length=100, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.TextField(verbose_name='經歷內容'),
        ),
    ]
