# Generated by Django 5.1 on 2024-08-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_experience_date_alter_experience_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexstory',
            options={'verbose_name': '封面故事（會在網頁上方跑馬燈）', 'verbose_name_plural': '封面故事列表'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '分組老師', 'verbose_name_plural': '老師列表'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='title',
        ),
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.CharField(blank=True, max_length=500, verbose_name='組別'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='default', max_length=500, verbose_name='老師姓名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(verbose_name='活動介紹'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.CharField(max_length=100, verbose_name='場地'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='poster',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/activities/', verbose_name='海報圖'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_type',
            field=models.CharField(max_length=100, verbose_name='票價（例：200/300/500）'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='program',
            field=models.JSONField(default=list, verbose_name='演出內容（曲目）'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ticket',
            field=models.JSONField(default=list, verbose_name='票種清單'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=500, verbose_name='活動/演出標題'),
        ),
        migrations.AlterField(
            model_name='indexstory',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='indexstory',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述（不超過10個字）'),
        ),
        migrations.AlterField(
            model_name='indexstory',
            name='image',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/index_stories/', verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='indexstory',
            name='place',
            field=models.CharField(blank=True, max_length=100, verbose_name='場地'),
        ),
        migrations.AlterField(
            model_name='indexstory',
            name='title',
            field=models.CharField(max_length=500, verbose_name='封面故事標題'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, verbose_name='老師簡歷'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/teachers/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, verbose_name='演出內容敘述'),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='youtube內嵌網址(請點選youtube分享)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/videos/', verbose_name='封面照'),
        ),
        migrations.AlterField(
            model_name='video',
            name='performer',
            field=models.CharField(max_length=100, verbose_name='演出者'),
        ),
        migrations.AlterField(
            model_name='video',
            name='place',
            field=models.CharField(max_length=100, verbose_name='演出場地'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=500, verbose_name='youtube網址'),
        ),
    ]
