# Generated by Django 5.1 on 2024-08-17 15:47

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_indexstory_options_alter_teacher_options_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='請以逗號分隔標籤', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='請以逗號分隔標籤', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='請以逗號分隔標籤', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
