import { Link } from "react-router-dom";

export const conductorData = [
  {
    index: 1,
    name: "小佳佳",
    description:
      "Ant Design, a design language for background applications, is refined by Ant UED Team.",
    content:
      "We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.",
    img: "https://gw.alipayobjects.com/zos/rmsportal/mqaQswcyDLcXyDKnZfES.png",
  },
  {
    index: 2,
    name: "彭筱和",
    description: "hi",
    content: "content",
    img: "https://images.unsplash.com/photo-1602694251352-c8040a589547?q=80&w=2248&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

export const teacherData = [
  {
    title: "笛子／蔡小靜",
    description:
      "畢業於臺北市立大學音樂系。主修笛。為竹音文化事業有限公司、臺北市演藝團隊-竹音音樂·Ching Music創辦人，並任教於臺北市成德國小、建中山國樂社笛子分部老師，致力國樂教學、推廣與演奏。現隨劉穎蓉老師學習尺八，追求更寬廣的音樂內涵與視野。",
    img: "https://images.unsplash.com/photo-1484557985045-edf25e08da73?q=80&w=2273&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    title: "笙／莊小涵",
    description:
      "畢業於國立臺灣戲曲學院戲曲音樂學系。主修傳統笙、三十六簧笙，副修鋼琴。曾榮獲2016宏福杯中國笙文化國際藝術節海外傳統笙青年組銀獎、2015臺北市學生音樂比賽東區大專組笙優等。 在專業領域方面多次參與明華園戲劇總團、國光劇團、中華國樂團、簪纓國樂團、草山樂坊、台北和樂集、桃園樂友絲竹室內樂團、九歌民族管絃樂團、台北市立國樂團等國內外演出活動及比賽。",
  },
  {
    title: "嗩吶／余小舜",
    description:
      "畢業於中國文化大學，音樂碩士學位，主修嗩吶，曾任蘇州民族管弦樂團嗩吶演奏員、采風樂坊兼任團員、臺北市立國樂團樂季協演團員，現為獨立音樂製作人、演奏家。2017參與庾澄慶《西哈遊記》專輯錄製、2012采風樂坊《無極》專輯錄製。2014受託義大利國際藝術節演出團體配樂編曲、2013首度發表絲竹樂作品《旅程》。",
  },
  {
    title: "揚琴／王小琳",
    description:
      "臺中市人，畢業於國立臺灣藝術大學中國音樂系碩士班演奏組，在學期間獲得多屆音樂比賽優勝。近年致力於教學，任教於臺北市復興高中音樂班、基隆高中音樂班、臺北市成德國小、新北市重陽國小、新北市光華國小、臺中市惠文中學等多所社團，更在蘇澳士敏國小推動全校學揚琴的特色教學。教學嚴謹， 2022年於臺大雅頌坊與洪寬倫老師籌劃師生重奏音樂會，大獲好評。王君音樂風格細緻，樂團經驗豐富，多方嘗試國樂團、管弦樂團、爵士樂、京劇等合作演出，演奏足跡遍及臺灣與海外各地。",
  },
  {
    title: "柳阮／蔡小彤",
    description:
      "現任臺北市立國樂團中阮兼三弦團員。國立臺南藝術大學民族音樂學研究所文學碩士、藝術學士。專精柳琴、阮咸、三弦等彈撥樂器。從小即多次榮獲各項全國音樂比賽柳琴組第一名。舞台經驗豐富，與簡文彬、瞿春泉、何文川、許瀞心等多位著名指揮合作，擔任柳琴、三弦獨奏，演出足跡遍佈中國、日本、美國等地。所教學生皆於比賽中獲得佳績，以及擔任音樂比賽評審。",
  },
];

export const experiencesData = [
  {
    date: "112年10月",
    experience: "參與臺北市學生音樂比賽國小絲竹室內樂B組及國樂合奏B組比賽，榮獲雙料優等",
  },
  { date: "112年9月", experience: "參加天母SOGO中秋音樂會演出" },
  { date: "112年6月", experience: "於成德國小樂齡教室舉辦【111學年度第2學期期末成果發表音樂會】" },
  { date: "112年5月", experience: "絲竹樂團赴日本大阪中華學校辦理藝術參訪交流活動" },
  {
    date: "112年3月",
    experience: "參與全國學生音樂比賽國小絲竹室內樂B組及國樂合奏B組比賽，榮獲雙料優等",
  },
];

export const indexStoryData = [
  {
    index: 1,
    title: "十周年團慶音樂會",
    date: "時間 | 6月30日（日）",
    place: "地點 | 台北生技園區多功能廳",
    img: "./images/home2.png",
    url: "",
  },
  {
    index: 2,
    title: "慶功宴",
    date: "時間 | 7月1日（一）",
    place: "地點 | 樂雅樂",
    img: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    index: 3,
    title: "十週年紀念品",
    date: "7月1日～7月31日 期間限定！",
    place: "數量有限，賣完就沒有囉！",
    img: "https://images.unsplash.com/photo-1518082049942-62a4e31b18d3?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHN0YXRpb25hcnl8ZW58MHx8MHx8fDA%3D",
  },
];

export function IntroductionText() {
  return (
    <>
      <p>
        臺北市南港區成德國民小學國樂團創立於2014年初，由李佳馨老師、彭彥翰老師擔任指導老師暨樂團指揮，為南港區新興之國小國樂團。
      </p>
      <p>
        本團招收一至六年級學生，目前有70位社員、12位分部老師。本團合奏及各分部老師皆畢業於音樂系科班，年輕、充滿活力、專業經驗豐富，帶領成德國樂學子賣力學習。社團極力爭取各式表演機會，連年榮獲臺北市及全國學生音樂比賽絲竹室內樂、國樂合奏優等，演出經驗豐富，備受社區及親師生之肯定。
      </p>
    </>
  );
}

export const introMenu = [
  {
    label: (
      <Link to="/intro" style={{ textDecoration: "none" }}>
        指揮介紹
      </Link>
    ),
    key: "conductor",
  },
  {
    label: (
      <Link to="/intro" style={{ textDecoration: "none" }}>
        歷年重要演出、比賽經歷
      </Link>
    ),
    key: "experiences",
  },
];

export const videosData = [
  {
    title: "鑽石之眼 - 金牛座",
    img: "https://images.unsplash.com/photo-1531660963020-52ba84d92593?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGNvbmNlcnQlMjBoYWxsfGVufDB8fDB8fHww",
    performer: "王曉明",
    date: "111年4月5日",
    place: "蘆洲功學社音樂廳",
    url: "https://www.youtube.com/watch?v=n5rtWLCDopU",
    embed_url: "https://www.youtube.com/embed/n5rtWLCDopU?si=Lk4lLw4zwyP4v-LL",
  },
  {
    title: "台北狂想",
    img: "https://images.unsplash.com/photo-1458639817867-2c9d4c5dcad4?q=80&w=2338&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    performer: "國樂團",
    date: "112年5月3日",
    place: "音樂廳",
    url: "https://www.youtube.com/watch?v=xJBrQ6cX5CU",
    embed_url: "https://www.youtube.com/embed/f7qUiKtS2N4?si=864INDRw2NiMyUyB",
  },
];

export const activitiesData = [
  {
    index: "1",
    title: "2024年度巡迴公演-台北場",
    poster:
      "https://images.unsplash.com/photo-1485278537138-4e8911a13c02?q=80&w=2487&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",

    date: "2024.7.28 (日)",
    place: "台北生技園區多功能廳",
    price: "200/300/500",
    stageImage: "/images/stage.png",
    description: "",
    program: [
      {
        title: "花傘與蘭花",
        composer: "朱嘯林",
      },
      {
        title: "德音",
        composer: "李博禪",
      },
      {
        title: "那些年",
        composer: "邱士峰",
      },
      {
        title: "彩龍船",
        composer: "瞿春泉",
      },
      {
        title: "抒情變奏曲III",
        composer: "劉長遠",
      },
      {
        title: "成德國小校歌",
        composer: "林明學",
      },
      {
        title: "《走過成德》十週年紀錄片",
        composer: "",
      },
    ],
    ticket: [
      {
        key: "basic",
        category: "普通票",
        price: "100元",
        description: "",
      },
      {
        key: "rock",
        category: "搖滾區",
        price: "500元",
        description: "",
      },
      {
        key: "vip",
        category: "VIP",
        price: "0元",
        description: "請出示貴賓邀請卡，可免費索取節目單",
      },
      {
        key: "elder",
        category: "敬老票",
        discount: "8折優惠",
        price: "80元",
        description: "請攜帶相關證明文件",
      },
    ],
  },
  {
    index: "2",
    title: "2024年度巡迴公演-高雄場",
    poster:
      "https://images.unsplash.com/photo-1485278537138-4e8911a13c02?q=80&w=2487&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    date: "2024.8.3 (六)",
    place: "衛武營國家藝術文化中心",
    price: "500",
    description: "",
  },
  {
    index: "3",
    title: "十周年團慶音樂會",
    poster: "/images/poster.jpg",
    date: "2024.6.30 (日)",
    place: "衛武營國家藝術文化中心",
    price: "500",
    description: "",
  },
];

export const albumsData = [
  {
    index: 1,
    title: "2024春遊",
    date: "2024.2.5",
    indexImg:
      "https://plus.unsplash.com/premium_photo-1664361480872-6416aab14696?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dHJhdmVsfGVufDB8fDB8fHww",
  },
  {
    index: 2,
    title: "113學年度上學期成果發表",
    date: "2024.1.5",
    indexImg:
      "https://images.unsplash.com/photo-1499442711659-a9566695faed?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cHJhY3RpY2V8ZW58MHx8MHx8fDA%3D",
    images: [],
  },
  {
    index: 3,
    title: "2023慶功宴",
    date: "2023.7.2",
    indexImg:
      "https://images.unsplash.com/photo-1481671703460-040cb8a2d909?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGZvb2R8ZW58MHx8MHx8fDA%3D",
    images: [],
  },
  {
    index: 4,
    title: "2023夏遊",
    date: "2023.8.30",
    indexImg:
      "https://plus.unsplash.com/premium_photo-1664361480872-6416aab14696?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dHJhdmVsfGVufDB8fDB8fHww",
    images: [],
  },
  {
    index: 5,
    title: "112學年度下學期成果發表",
    date: "2023.6.25",
    indexImg:
      "https://images.unsplash.com/photo-1499442711659-a9566695faed?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cHJhY3RpY2V8ZW58MHx8MHx8fDA%3D",
    images: [],
  },
  {
    index: 6,
    title: "2023慶功宴",
    date: "2023.7.2",
    indexImg:
      "https://images.unsplash.com/photo-1481671703460-040cb8a2d909?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGZvb2R8ZW58MHx8MHx8fDA%3D",
    images: [],
  },
];

export const newsData = [
  {
    index: 1,
    title: "News1",
    content:
      "Ant Design, a design language for background applications, is refined by Ant UED Team",
    date: "2024.2.1",
    category: "ticket",
    img: "",
  },
  {
    index: 2,
    title: "News2",
    content:
      "Ant Design, a design language for background applications, is refined by Ant UED Team",
    date: "2024.3.1",
    category: "announcement",
    img: "",
  },
  {
    index: 3,
    title: "News3",
    content:
      "Ant Design, a design language for background applications, is refined by Ant UED Team",
    date: "2024.4.1",
    category: "",
    img: "",
  },
  {
    index: 4,
    title: "News4",
    content:
      "Ant Design, a design language for background applications, is refined by Ant UED Team",
    date: "2024.5.1",
    category: "",
    img: "",
  },
  {
    index: 5,
    title: "News5",
    content:
      "Ant Design, a design language for background applications, is refined by Ant UED Team",
    date: "2024.6.1",
    category: "",
    img: "",
  },
];

export const productsData = [
  {
    "服裝、配件": [
      {
        index: 1,
        title: "紀念T",
        price: 200,
        discount_price: 180,
        img: "/images/團T正面.png",
        description: "",
        total_amount: 10,
        status: "enable",
      },
      {
        index: 2,
        title: "棒球帽",
        price: 100,
        discount_price: 90,
        img: "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8aGF0fGVufDB8fDB8fHww",
        description: "",
        total_amount: 10,
        status: "enable",
      },
    ],
  },
  {
    文具: [
      {
        index: 3,
        title: "譜夾",
        price: 150,
        discount_price: 135,
        img: "/images/譜夾1.png",
        description: "",
        total_amount: 10,
        status: "enable",
      },
      {
        index: 4,
        title: "卡套",
        price: 100,
        discount_price: 90,
        img: "https://images.unsplash.com/photo-1532630571098-79a3d222b00d?q=80&w=2472&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "",
        total_amount: 10,
        status: "disable",
      },
    ],
  },
  {
    歷年演出相關: [
      {
        index: 5,
        title: "DVD",
        price: 300,
        discount_price: 270,
        img: "https://plus.unsplash.com/premium_photo-1682125554685-2e52be3112db?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8RFZEfGVufDB8fDB8fHww",
        description: "",
        total_amount: 10,
        status: "enable",
      },
      {
        index: 6,
        title: "CD",
        price: 200,
        discount_price: 180,
        img: "https://images.unsplash.com/photo-1618034100983-e1d78be0dc80?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8RFZEfGVufDB8fDB8fHww",
        description: "",
        total_amount: 10,
        status: "enable",
      },
    ],
  },
  {
    其他: [
      {
        index: 7,
        title: "保溫杯",
        price: 300,
        discount_price: "270",
        img: "https://plus.unsplash.com/premium_photo-1664527305901-db3d4e724d15?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Ym90dGxlfGVufDB8fDB8fHww",
        description: "",
        total_amount: 10,
        status: "enable",
      },
      {
        index: 8,
        title: "帆布包",
        price: 300,
        discount_price: "270",
        img: "/images/bag_0.png",
        description: "",
        total_amount: 10,
        status: "discount",
      },
    ],
  },
];

export const productsData2 = [
  {
    index: 1,
    title: "紀念T",
    price: 200,
    discount_price: 180,
    img: "/images/團T正面.png",
    description: "",
    total_amount: 10,
    status: "enable",
    category: "服裝、配件",
  },
  {
    index: 2,
    title: "棒球帽",
    price: 100,
    discount_price: 90,
    img: "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8aGF0fGVufDB8fDB8fHww",
    description: "",
    total_amount: 10,
    status: "enable",
    category: "服裝、配件",
  },
  {
    index: 3,
    title: "譜夾",
    price: 150,
    discount_price: 135,
    img: "/images/譜夾1.jpg",
    description: "",
    total_amount: 10,
    status: "enable",
    category: "文具",
  },
  {
    index: 4,
    title: "卡套",
    price: 100,
    discount_price: 90,
    img: "https://images.unsplash.com/photo-1532630571098-79a3d222b00d?q=80&w=2472&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "",
    total_amount: 10,
    status: "disable",
    category: "文具",
  },

  {
    index: 5,
    title: "DVD",
    price: 300,
    discount_price: 270,
    img: "https://plus.unsplash.com/premium_photo-1682125554685-2e52be3112db?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8RFZEfGVufDB8fDB8fHww",
    description: "",
    total_amount: 10,
    status: "enable",
    category: "演出影音",
  },
  {
    index: 6,
    title: "CD",
    price: 200,
    discount_price: 180,
    img: "https://images.unsplash.com/photo-1618034100983-e1d78be0dc80?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8RFZEfGVufDB8fDB8fHww",
    description: "",
    total_amount: 10,
    status: "enable",
    category: "演出影音",
  },

  {
    index: 7,
    title: "保溫杯",
    price: 300,
    discount_price: "270",
    img: "https://plus.unsplash.com/premium_photo-1664527305901-db3d4e724d15?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Ym90dGxlfGVufDB8fDB8fHww",
    description: "",
    total_amount: 10,
    status: "enable",
    category: "其他",
  },
  {
    index: 8,
    title: "帆布包",
    price: 300,
    discount_price: "270",
    img: "/images/bag_0.png",
    description: "",
    total_amount: 10,
    status: "discount",
    category: "其他",
  },
];

export const addressData = {
  臺北市: [
    "中正區",
    "大同區",
    "中山區",
    "松山區",
    "大安區",
    "萬華區",
    "信義區",
    "士林區",
    "北投區",
    "內湖區",
    "南港區",
    "文山區",
  ],
  新北市: [
    "萬里區",
    "金山區",
    "板橋區",
    "汐止區",
    "深坑區",
    "石碇區",
    "瑞芳區",
    "平溪區",
    "雙溪區",
    "貢寮區",
    "新店區",
    "坪林區",
    "烏來區",
    "永和區",
    "中和區",
    "土城區",
    "三峽區",
    "樹林區",
    "鶯歌區",
    "三重區",
    "新莊區",
    "泰山區",
    "林口區",
    "蘆洲區",
    "五股區",
    "八里區",
    "淡水區",
    "三芝區",
    "石門區",
  ],
  基隆市: ["仁愛區", "信義區", "中正區", "中山區", "安樂區", "暖暖區", "七堵區"],
  桃園市: [
    "中壢區",
    "平鎮區",
    "龍潭區",
    "楊梅區",
    "新屋區",
    "觀音區",
    "桃園區",
    "龜山區",
    "八德區",
    "大溪區",
    "復興區",
    "大園區",
    "蘆竹區",
  ],
  新竹市: ["東區", "北區", "香山區"],
  新竹縣: [
    "竹北市",
    "湖口鄉",
    "新豐鄉",
    "新埔鎮",
    "關西鎮",
    "芎林鄉",
    "寶山鄉",
    "竹東鎮",
    "五峰鄉",
    "橫山鄉",
    "尖石鄉",
    "北埔鄉",
    "峨眉鄉",
  ],
  苗栗縣: [
    "竹南鎮",
    "頭份市",
    "三灣鄉",
    "南庄鄉",
    "獅潭鄉",
    "後龍鎮",
    "通霄鎮",
    "苑裡鎮",
    "苗栗市",
    "造橋鄉",
    "頭屋鄉",
    "公館鄉",
    "大湖鄉",
    "泰安鄉",
    "銅鑼鄉",
    "三義鄉",
    "西湖鄉",
    "卓蘭鎮",
  ],
  臺中市: [
    "中區",
    "東區",
    "南區",
    "西區",
    "北區",
    "北屯區",
    "西屯區",
    "南屯區",
    "太平區",
    "大里區",
    "霧峰區",
    "烏日區",
    "豐原區",
    "后里區",
    "石岡區",
    "東勢區",
    "和平區",
    "新社區",
    "潭子區",
    "大雅區",
    "神岡區",
    "大肚區",
    "沙鹿區",
    "龍井區",
    "梧棲區",
    "清水區",
    "大甲區",
    "外埔區",
    "大安區",
  ],
  彰化縣: [
    "彰化市",
    "芬園鄉",
    "花壇鄉",
    "秀水鄉",
    "鹿港鎮",
    "福興鄉",
    "線西鄉",
    "和美鎮",
    "伸港鄉",
    "員林市",
    "社頭鄉",
    "永靖鄉",
    "埔心鄉",
    "溪湖鎮",
    "大村鄉",
    "埔鹽鄉",
    "田中鎮",
    "北斗鎮",
    "田尾鄉",
    "埤頭鄉",
    "溪州鄉",
    "竹塘鄉",
    "二林鎮",
    "大城鄉",
    "芳苑鄉",
    "二水鄉",
  ],
  南投縣: [
    "南投市",
    "中寮鄉",
    "草屯鎮",
    "國姓鄉",
    "埔里鎮",
    "仁愛鄉",
    "名間鄉",
    "集集鎮",
    "水里鄉",
    "魚池鄉",
    "信義鄉",
    "竹山鎮",
    "鹿谷鄉",
  ],
  雲林縣: [
    "斗南鎮",
    "大埤鄉",
    "虎尾鎮",
    "土庫鎮",
    "褒忠鄉",
    "東勢鄉",
    "臺西鄉",
    "崙背鄉",
    "麥寮鄉",
    "斗六市",
    "林內鄉",
    "古坑鄉",
    "莿桐鄉",
    "西螺鎮",
    "二崙鄉",
    "北港鎮",
    "水林鄉",
    "口湖鄉",
    "四湖鄉",
    "元長鄉",
  ],
  嘉義市: ["東區", "西區"],
  嘉義縣: [
    "番路鄉",
    "梅山鄉",
    "竹崎鄉",
    "阿里山鄉",
    "中埔鄉",
    "大埔鄉",
    "水上鄉",
    "鹿草鄉",
    "太保市",
    "朴子市",
    "東石鄉",
    "六腳鄉",
    "新港鄉",
    "民雄鄉",
    "大林鎮",
    "溪口鄉",
    "義竹鄉",
    "布袋鎮",
  ],
  臺南市: [
    "中西區",
    "東區",
    "南區",
    "北區",
    "安平區",
    "安南區",
    "永康區",
    "歸仁區",
    "新化區",
    "左鎮區",
    "玉井區",
    "楠西區",
    "南化區",
    "仁德區",
    "關廟區",
    "龍崎區",
    "官田區",
    "麻豆區",
    "佳里區",
    "西港區",
    "七股區",
    "將軍區",
    "學甲區",
    "北門區",
    "新營區",
    "後壁區",
    "白河區",
    "東山區",
    "六甲區",
    "下營區",
    "柳營區",
    "鹽水區",
    "善化區",
    "大內區",
    "山上區",
    "新市區",
    "安定區",
  ],
  高雄市: [
    "新興區",
    "前金區",
    "苓雅區",
    "鹽埕區",
    "鼓山區",
    "旗津區",
    "前鎮區",
    "三民區",
    "楠梓區",
    "小港區",
    "左營區",
    "仁武區",
    "大社區",
    "岡山區",
    "路竹區",
    "阿蓮區",
    "田寮區",
    "燕巢區",
    "橋頭區",
    "梓官區",
    "彌陀區",
    "永安區",
    "湖內區",
    "鳳山區",
    "大寮區",
    "林園區",
    "鳥松區",
    "大樹區",
    "旗山區",
    "美濃區",
    "六龜區",
    "內門區",
    "杉林區",
    "甲仙區",
    "桃源區",
    "那瑪夏區",
    "茂林區",
    "茄萣區",
  ],
  屏東縣: [
    "屏東市",
    "三地門鄉",
    "霧臺鄉",
    "瑪家鄉",
    "九如鄉",
    "里港鄉",
    "高樹鄉",
    "鹽埔鄉",
    "長治鄉",
    "麟洛鄉",
    "竹田鄉",
    "內埔鄉",
    "萬丹鄉",
    "潮州鎮",
    "泰武鄉",
    "來義鄉",
    "萬巒鄉",
    "崁頂鄉",
    "新埤鄉",
    "南州鄉",
    "林邊鄉",
    "東港鎮",
    "琉球鄉",
    "佳冬鄉",
    "新園鄉",
    "枋寮鄉",
    "枋山鄉",
    "春日鄉",
    "獅子鄉",
    "車城鄉",
    "牡丹鄉",
    "恆春鎮",
    "滿州鄉",
  ],
  宜蘭縣: [
    "宜蘭市",
    "頭城鎮",
    "礁溪鄉",
    "壯圍鄉",
    "員山鄉",
    "羅東鎮",
    "三星鄉",
    "大同鄉",
    "五結鄉",
    "冬山鄉",
    "蘇澳鎮",
    "南澳鄉",
    "釣魚臺",
  ],
  花蓮縣: [
    "花蓮市",
    "新城鄉",
    "秀林鄉",
    "吉安鄉",
    "壽豐鄉",
    "鳳林鎮",
    "光復鄉",
    "豐濱鄉",
    "瑞穗鄉",
    "萬榮鄉",
    "玉里鎮",
    "卓溪鄉",
    "富里鄉",
  ],
  臺東縣: [
    "臺東市",
    "綠島鄉",
    "蘭嶼鄉",
    "延平鄉",
    "卑南鄉",
    "鹿野鄉",
    "關山鎮",
    "海端鄉",
    "池上鄉",
    "東河鄉",
    "成功鎮",
    "長濱鄉",
    "太麻里鄉",
    "金峰鄉",
    "大武鄉",
    "達仁鄉",
  ],
  澎湖縣: ["馬公市", "西嶼鄉", "望安鄉", "七美鄉", "白沙鄉", "湖西鄉"],
  金門縣: ["金沙鎮", "金湖鎮", "金寧鄉", "金城鎮", "烈嶼鄉", "烏坵鄉"],
  連江縣: ["南竿鄉", "北竿鄉", "莒光鄉", "東引鄉"],
};

export const cityData = [
  "臺北市",
  "新北市",
  "桃園市",
  "臺中市",
  "臺南市",
  "高雄市",
  "基隆市",
  "新竹市",
  "嘉義市",
  "新竹縣",
  "苗栗縣",
  "彰化縣",
  "南投縣",
  "雲林縣",
  "嘉義縣",
  "屏東縣",
  "臺東縣",
  "花蓮縣",
  "澎湖縣",
];

export const orderList = [
  {
    name: "test1",
    phone: "123456778",
    email: "123@123",
    ticket: { NT$200: 2 },
    product: [],
    totalPrice: 400,
  },
];
